### ISSUE TITLE
error when loading iceflow.jl and instantiating

### ISSUE THREAD

**Issue by waywardpidgeon** [luraess/julia-parallel-course-EGU21#11]
I am running a NVIDA GPU with Windows 11 and Julia 1.10.4. I have found all the directions in "Getting started" very helpful, indeed I am learing a lot on how to run Julia effectively.

However I get an error first "JLD not installed" (even through I believe it was) and then on instantiating again (from Julia and not the package env) I get a message indicating a CUDA or GPU installation problem. I have pasted the output below.

Many thanks - Kevin

**Comment by waywardpidgeon** [comment]
julia> using Pkg; Pkg.instantiate()
    Updating registry at `C:\Users\Kevin.DESKTOP-SVS3IFD\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: Unsatisfiable requirements detected for package GPUCompiler [61eb1bfa]:
 GPUCompiler [61eb1bfa] log:
 ├─possible versions are: 0.1.0-0.26.5 or uninstalled
 ├─restricted by julia compatibility requirements to versions: 0.22.0-0.26.5 or uninstalled
 └─restricted by compatibility requirements with CUDA [052768ef] to versions: [0.11.3-0.12.9, 0.13.3-0.17.3] — no versions left
   └─CUDA [052768ef] log:
     ├─possible versions are: 0.1.0-5.4.2 or uninstalled
     └─restricted to versions 3.1.0-3 by julia-parallel-course-EGU21 [7430b6d3], leaving only versions: 3.1.0-3.13.1
       └─julia-parallel-course-EGU21 [7430b6d3] log:
         ├─possible versions are: 0.0.0 or uninstalled
         └─julia-parallel-course-EGU21 [7430b6d3] is fixed to version 0.0.0
Stacktrace:
  [1] propagate_constraints!(graph::Pkg.Resolve.Graph, sources::Set{Int64}; log_events::Bool)
    @ Pkg.Resolve C:\Users\Kevin.DESKTOP-SVS3IFD\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\Resolve\graphtype.jl:1072
  [2] propagate_constraints! (repeats 2 times)
    @ C:\Users\Kevin.DESKTOP-SVS3IFD\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\Resolve\graphtype.jl:1008 [inlined]
  [3] simplify_graph!(graph::Pkg.Resolve.Graph, sources::Set{Int64}; clean_graph::Bool)
    @ Pkg.Resolve C:\Users\Kevin.DESKTOP-SVS3IFD\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\Resolve\graphtype.jl:1533
  [4] simplify_graph! (repeats 2 times)
    @ C:\Users\Kevin.DESKTOP-SVS3IFD\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\Resolve\graphtype.jl:1532 [inlined]
  [5] resolve_versions!(env::Pkg.Types.EnvCache, registries::Vector{…}, pkgs::Vector{…}, julia_version::VersionNumber, installed_only::Bool)
    @ Pkg.Operations C:\Users\Kevin.DESKTOP-SVS3IFD\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\Operations.jl:408
  [6] up(ctx::Pkg.Types.Context, pkgs::Vector{…}, level::Pkg.Types.UpgradeLevel; skip_writing_project::Bool, preserve::Nothing)
    @ Pkg.Operations C:\Users\Kevin.DESKTOP-SVS3IFD\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\Operations.jl:1538
  [7] up
    @ C:\Users\Kevin.DESKTOP-SVS3IFD\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\Operations.jl:1520 [inlined]
  [8] up(ctx::Pkg.Types.Context, pkgs::Vector{…}; level::Pkg.Types.UpgradeLevel, mode::Pkg.Types.PackageMode, preserve::Nothing, update_registry::Bool, skip_writing_project::Bool, kwargs::@Kwargs{})
    @ Pkg.API C:\Users\Kevin.DESKTOP-SVS3IFD\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\API.jl:351
  [9] up
    @ C:\Users\Kevin.DESKTOP-SVS3IFD\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\API.jl:326 [inlined]
 [10] up
    @ C:\Users\Kevin.DESKTOP-SVS3IFD\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\API.jl:164 [inlined]
 [11] instantiate(ctx::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Base.BinaryPlatforms.Platform, allow_build::Bool, allow_autoprecomp::Bool, kwargs::@Kwargs{})
    @ Pkg.API C:\Users\Kevin.DESKTOP-SVS3IFD\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\API.jl:1797
 [12] instantiate
    @ C:\Users\Kevin.DESKTOP-SVS3IFD\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\API.jl:1773 [inlined]
 [13] instantiate()
    @ Pkg.API C:\Users\Kevin.DESKTOP-SVS3IFD\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Pkg\src\API.jl:1772
 [14] top-level scope
    @ REPL[9]:1
Some type information was truncated. Use `show(err)` to see complete types.

**Comment by waywardpidgeon** [comment]
Also after rm JLD and attempting to add it again I get:
(julia-parallel-course-EGU21) pkg> add JLD
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package GPUCompiler [61eb1bfa]:
 GPUCompiler [61eb1bfa] log:
 ├─possible versions are: 0.1.0-0.26.5 or uninstalled
 ├─restricted by julia compatibility requirements to versions: 0.22.0-0.26.5 or uninstalled
 └─restricted by compatibility requirements with CUDA [052768ef] to versions: [0.11.3-0.12.9, 0.13.3-0.17.3] — no versions left
   └─CUDA [052768ef] log:
     ├─possible versions are: 0.1.0-5.4.2 or uninstalled
     └─restricted to versions 3.1.0-3 by julia-parallel-course-EGU21 [7430b6d3], leaving only versions: 3.1.0-3.13.1
       └─julia-parallel-course-EGU21 [7430b6d3] log:
         ├─possible versions are: 0.0.0 or uninstalled
         └─julia-parallel-course-EGU21 [7430b6d3] is fixed to version 0.0.0

**Comment by waywardpidgeon** [comment]
Sorry - I am at home and don't have a GPU installed!! Please close this issue with my abject apologies - Kevin

**Comment by luraess** [comment]
Thanks for your interest!

You need a GPU in order to get CUDA or GPU backend functional. Also, if you hit issues with JLD, JLD2 may provide an alternative (although one may need to generate new input files). Last, the compat bounds are relatively old which may also lead to some issues. I am closing this for now, but do not hesitate to open an issue again if you hit anything that seems not working as expected.
